[language-server.efm]
command = "efm-langserver"

[language-server.hardhat]
command = "nomicfoundation-solidity-language-server"
args = ["--stdio"]

[[language]]
name = "solidity"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] },
  { name = "hardhat", except-features = [ "format" ] }
]
