-- subsetted from https://github.com/echasnovski/mini.clue/blob/main/lua/mini/clue.lua
-- stylua: ignore
return {
  { mode = "n", keys = "g0", desc = "Go to leftmost visible column" },
  { mode = "n", keys = "g8", desc = "Print hex value of char under cursor" },
  { mode = "n", keys = "ga", desc = "Print ascii value" },
  { mode = "n", keys = "g'", desc = "Jump to mark (don't affect jumplist)" },
  { mode = "n", keys = "g`", desc = "Jump to mark (don't affect jumplist)" },
  { mode = "x", keys = "g'", desc = "Jump to mark (don't affect jumplist)" },
  { mode = "x", keys = "g`", desc = "Jump to mark (don't affect jumplist)" },
  { mode = "n", keys = "gE", desc = "Go backwards to end of previous WORD" },
  { mode = "n", keys = "ge", desc = "Go backwards to end of previous word" },
  { mode = "n", keys = "gF", desc = "Edit file under cursor + jump line" },
  { mode = "n", keys = "gf", desc = "Edit file under cursor" },
  { mode = "n", keys = "gg", desc = "Go to line (def: first)" },
  { mode = "n", keys = "gi", desc = "Start Insert where it stopped" },
  { mode = "n", keys = "gN", desc = "Select previous search match" },
  { mode = "n", keys = "gn", desc = "Select next search match" },
  { mode = "n", keys = "gq", desc = "Format text (operator)" },
  { mode = "n", keys = "gv", desc = "Reselect previous Visual area" },
  { mode = "n", keys = "gw", desc = "Format text (non-LSP) + keep cursor (operator)" },
  { mode = "n", keys = "gx", desc = "Execute app for file under cursor" },
  { mode = "n", keys = "g<C-g>", desc = "Show information about cursor" },
  { mode = "n", keys = "g#", desc = "Search backwards word under cursor" },
  { mode = "n", keys = "g$", desc = "Go to rightmost visible column" },
  { mode = "n", keys = "g&", desc = "Repeat last `:s` on all lines" },
  { mode = "n", keys = "g*", desc = "Search word under cursor" },
  { mode = "n", keys = "g+", desc = "Go to newer text state" },
  { mode = "n", keys = "g,", desc = "Go to newer position in change list" },
  { mode = "n", keys = "g-", desc = "Go to older text state" },
  { mode = "n", keys = "g;", desc = "Go to older position in change list" },
  { mode = "n", keys = "g<", desc = "Display previous command output" },
  { mode = "n", keys = "g?", desc = "Rot13 encode (operator)" },
  { mode = "n", keys = "g@", desc = "Call 'operatorfunc' (operator)" },
  { mode = "n", keys = "g^", desc = "Go to leftmost visible non-whitespace" },
  { mode = "n", keys = "g~", desc = "Swap case (operator)" },

  { mode = "x", keys = "gf", desc = "Edit selected file" },
  { mode = "x", keys = "gq", desc = "Format selection" },
  { mode = "x", keys = "gw", desc = "Format selection (non-LSP) + keep cursor" },
  { mode = "x", keys = "g<C-a>", desc = "Increment with compound" },
  { mode = "x", keys = "g<C-g>", desc = "Show information about selection" },
  { mode = "x", keys = "g<C-x>", desc = "Decrement with compound" },
  { mode = "x", keys = "g?", desc = "Rot13 encode selection" },
}
